language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pgaida/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pgaida/docker-react npm run test